-- SQL para popular a tabela technicians no Supabase
-- Gerado automaticamente a partir de BaseTecnicos.xlsx + Databricks
-- Execute no Supabase SQL Editor

INSERT INTO technicians (name, email, phone, region, supervisor_name, supervisor_email, databricks_name, databricks_id, active, created_at)
VALUES
  ('RAIMUNDO NAZARENO DA SILVA NAVARRO', 'rnavarro@positivo.com.br', '5538998350626', 'AC', 'Deyvson Leopoldino Da Silva', NULL, 'RAIMUNDO NAZARENO DA SILVA NAVARRO', 15163, true, NOW()),
  ('ADRIANO ATHAYDE PEDROSA', 'aathayde@positivo.com.br', '5582988488560', 'AL', 'Deyvson Leopoldino Da Silva', NULL, 'ADRIANO ATHAYDE PEDROSA', 17306, true, NOW()),
  ('ANTONIO ENEAS BARROS DE FIGUEIREDO', 'antoniof@positivo.com.br', '5541999318927', 'AL', 'Deyvson Leopoldino Da Silva', NULL, 'ANTONIO ENEAS BARROS DE FIGUEIREDO', 15641, true, NOW()),
  ('JUAREZ JACKSON DE LIMA SANTOS', NULL, NULL, 'AL', 'Deyvson Leopoldino Da Silva', NULL, 'JUAREZ JACKSON DE LIMA SANTOS', 12939, true, NOW()),
  ('MARIO LUCAS LIMA LOPES', 'mario.lopes@positivo.com.br', '5541991940369', 'AM', 'Deyvson Leopoldino Da Silva', NULL, 'MARIO LUCAS LIMA LOPES', 15872, true, NOW()),
  ('WASHIGTON LOPES', 'washington.filho@positivo.com.br', '5531999427680', 'AM', 'Deyvson Leopoldino Da Silva', NULL, 'WASHIGTON LOPES', 15043, true, NOW()),
  ('DIOGO VICTOR DO REGO VAZ', 'DIOGO.VAZ@POSITIVO.COM.BR', '5596991881252', 'AP', 'Deyvson Leopoldino Da Silva', NULL, 'DIOGO VICTOR DO REGO VAZ', 17301, true, NOW()),
  ('CARLOS ALBERTO CAMPINHO PASSOS', 'carlosp@positivo.com.br', '5541992511659', 'BA', 'Maroe Kao Da Silva', NULL, 'CARLOS ALBERTO CAMPINHO PASSOS', 15608, true, NOW()),
  ('DIEGO DO ROSARIO ARAUJO', 'diegoa@positivo.com.br', '5541991877590', 'BA', 'Maroe Kao Da Silva', NULL, 'DIEGO DO ROSARIO ARAUJO', 10725, true, NOW()),
  ('FELIPE DURVAL DIAS DA SILVA', NULL, NULL, 'BA', 'Maroe Kao Da Silva', NULL, 'FELIPE DURVAL DIAS DA SILVA', 13236, true, NOW()),
  ('ICARO SENA SOUZA', NULL, NULL, 'BA', 'Maroe Kao Da Silva', NULL, 'ICARO SENA SOUZA', 11709, true, NOW()),
  ('JOÃO HENRIQUE DE ANDRADE FIDELIS', 'joaof@positivo.com.br', NULL, 'BA', 'Maroe Kao Da Silva', NULL, 'JOÃO HENRIQUE DE ANDRADE FIDELIS', 17042, true, NOW()),
  ('LEONARDO SANTOS CRUZ', NULL, NULL, 'BA', 'Maroe Kao Da Silva', NULL, 'LEONARDO SANTOS CRUZ', 15313, true, NOW()),
  ('MARIA DE NAZARE SANTOS SOARES', 'maria.soares@positivo.com.br', NULL, 'BA', 'Maroe Kao Da Silva', NULL, 'MARIA DE NAZARE SANTOS SOARES', 15311, true, NOW()),
  ('MOISES ALONSO RUAS FILHO', 'moisesf@positivo.com.br', '5541991940369', 'BA', 'Maroe Kao Da Silva', NULL, 'MOISES ALONSO RUAS FILHO', 14318, true, NOW()),
  ('NOEL OLIVEIRA FERREIRA JUNIOR', 'noel.junior@positivo.com.br', '5541992243924', 'BA', 'Maroe Kao Da Silva', NULL, 'NOEL OLIVEIRA FERREIRA JUNIOR', 15241, true, NOW()),
  ('Rubens Carlos Gonçalves Filho', 'rubensf@positivo.com.br', '5571999137127', 'BA', 'Maroe Kao Da Silva', NULL, 'RUBENS CARLOS GONÇALVES FILHO', 15548, true, NOW()),
  ('VINICIUS NERIS LIMA', 'vinicius.lima@positivo.com.br', '5541992571485', 'BA', 'Maroe Kao Da Silva', NULL, 'VINICIUS NERIS LIMA', 17181, true, NOW()),
  ('VITOR LUIS MOTA COELHO', 'vitorl@positivo.com.br', '5541992414327', 'BA', 'Maroe Kao Da Silva', NULL, 'VITOR LUIS MOTA COELHO', 13856, true, NOW()),
  ('ALUIZIO FELIX DA SILVA NETO', 'aluiziof@positivo.com.br', '5551996142219', 'CE', 'Deyvson Leopoldino Da Silva', NULL, 'ALUIZIO FELIX DA SILVA NETO', 15717, true, NOW()),
  ('AUDISIO BEZERRA DO NASCIMENTO JUNIOR', 'audisiob@positivo.com.br', '5511996085945', 'CE', 'Deyvson Leopoldino Da Silva', NULL, 'AUDISIO BEZERRA DO NASCIMENTO JUNIOR', 17124, true, NOW()),
  ('DAVID BEZERRA DOS SANTOS', 'david.santos@positivo.com.br', '5585987520222', 'CE', 'Deyvson Leopoldino Da Silva', NULL, 'DAVID BEZERRA DOS SANTOS', 12547, true, NOW()),
  ('FAGNER MARQUES DA SILVA', 'fagner.silva@positivo.com.br', '5585988266974', 'CE', 'Deyvson Leopoldino Da Silva', NULL, 'FAGNER MARQUES DA SILVA', 11362, true, NOW()),
  ('JEFERSON ALVES BEZERRA', 'jefersonb@positivo.com.br', '5588996061439', 'CE', 'Deyvson Leopoldino Da Silva', NULL, 'JEFERSON ALVES BEZERRA', 15722, true, NOW()),
  ('JOAO LUIS DOS REIS LIMA', NULL, NULL, 'CE', 'Deyvson Leopoldino Da Silva', NULL, 'JOAO LUIS DOS REIS LIMA', 13199, true, NOW()),
  ('LEVI LOPES FELIX', NULL, NULL, 'CE', 'Deyvson Leopoldino Da Silva', NULL, 'LEVI LOPES FELIX', 14178, true, NOW()),
  ('LUIZ NONATO CARVALHO BRAID', NULL, NULL, 'CE', 'Deyvson Leopoldino Da Silva', NULL, 'LUIZ NONATO CARVALHO BRAID', 15061, true, NOW()),
  ('RICARDO ROBERTSON DA SILVA CAMPOS', NULL, NULL, 'CE', 'Deyvson Leopoldino Da Silva', NULL, 'RICARDO ROBERTSON DA SILVA CAMPOS', 13451, true, NOW()),
  ('ANDRE ANTONIO MENINGHIN ALVES', 'andre.alves@positivo.com.br', '5511915560055', 'MG', 'Nina Carla Bitencourt Aguilar', NULL, 'ANDRE ANTONIO MENINGHIN ALVES', 15306, true, NOW()),
  ('BRUNO VITOR FERRAZ DA CRUZ', 'brunov@positivo.com.br', '5532999417970', 'MG', 'Nina Carla Bitencourt Aguilar', NULL, 'BRUNO VITOR FERRAZ DA CRUZ', 12856, true, NOW()),
  ('DANIEL ANTONIO SILVA OLIVEIRA', 'daniel.oliveira@positivo.com.br', '5531999163116', 'MG', 'Nina Carla Bitencourt Aguilar', NULL, 'DANIEL ANTONIO SILVA OLIVEIRA', 15110, true, NOW()),
  ('DANIEL LIMA CRUZ DE OLIVEIRA', 'danielo@positivo.com.br', '5531993079866', 'MG', 'Nina Carla Bitencourt Aguilar', NULL, 'DANIEL LIMA CRUZ DE OLIVEIRA', 15318, true, NOW()),
  ('DANIEL LUIZ TAVARES', 'daniel.tavares@positivo.com.br', '5531984085045', 'MG', 'Nina Carla Bitencourt Aguilar', NULL, 'DANIEL LUIZ TAVARES', 15111, true, NOW()),
  ('GABRIEL TEODORO', 'gabriel.teodoro@positivo.com.br', '5531971304970', 'MG', 'Nina Carla Bitencourt Aguilar', NULL, 'GABRIEL TEODORO', 15112, true, NOW()),
  ('GLAYDSON JUNIO RODRIGUES PASSOS', 'glaydsonp@positivo.com.br', NULL, 'MG', 'Nina Carla Bitencourt Aguilar', NULL, 'GLAYDSON JUNIO RODRIGUES PASSOS', 15365, true, NOW()),
  ('IGOR VIEIRA MENDES LUZ', 'iluz@positivo.com.br', NULL, 'MG', 'Nina Carla Bitencourt Aguilar', NULL, 'IGOR VIEIRA MENDES LUZ', 16416, true, NOW()),
  ('IZABELA PAIM DE PAULA OLIVEIRA', 'izabelao@positivo.com.br', '5531999836088', 'MG', 'Nina Carla Bitencourt Aguilar', NULL, 'IZABELA PAIM DE PAULA OLIVEIRA', 17107, true, NOW()),
  ('JONATA SILVA PINHO', 'jonata.pinho@positivo.com.br', NULL, 'MG', 'Nina Carla Bitencourt Aguilar', NULL, 'JONATA SILVA PINHO', 17261, true, NOW()),
  ('JONATHAS VINÍCIUS SANTANA', 'jonathas.ana@positivo.com.br', '5531992908671', 'MG', 'Nina Carla Bitencourt Aguilar', NULL, 'JONATHAS VINÍCIUS SANTANA', 17118, true, NOW()),
  ('JULIO CEZAR LOPES DOS SANTOS TOMAZ', 'julio.tomaz@positivo.com.br', '5531999110741', 'MG', 'Nina Carla Bitencourt Aguilar', NULL, 'JULIO CEZAR LOPES DOS SANTOS TOMAZ', 16903, true, NOW()),
  ('LEDSON DOS REIS VILELA MISAEL', 'ledsonm@positivo.com.br', '5534998808453', 'MG', 'Nina Carla Bitencourt Aguilar', NULL, 'LEDSON DOS REIS VILELA MISAEL', 15533, true, NOW()),
  ('LEONARDO FRANCISCO NEVES DA SILVA', 'leonardons@positivo.com.br', '5531996494439', 'MG', 'Nina Carla Bitencourt Aguilar', NULL, 'LEONARDO FRANCISCO NEVES DA SILVA', 15113, true, NOW()),
  ('LINCONN ALVES LIMA', 'linconnl@positivo.com.br', NULL, 'MG', 'Nina Carla Bitencourt Aguilar', NULL, 'LINCONN ALVES LIMA', 15545, true, NOW()),
  ('LUCAS EDUARDO FERNANDES DE OLIVEIRA', NULL, NULL, 'MG', 'Nina Carla Bitencourt Aguilar', NULL, 'LUCAS EDUARDO FERNANDES DE OLIVEIRA', 15106, true, NOW()),
  ('LUCAS ROCHA 2', NULL, NULL, 'MG', 'Nina Carla Bitencourt Aguilar', NULL, 'LUCAS ROCHA 2', 15516, true, NOW()),
  ('LUCAS ROCHA DOS SANTOS', 'lrocha@positivo.com.br', '5534984079841', 'MG', 'Nina Carla Bitencourt Aguilar', NULL, 'LUCAS ROCHA DOS SANTOS', 15515, true, NOW()),
  ('LUCAS WENDERSON DE SANDES PEREIRA', 'lucasp@positivo.com.br', '5531997211034', 'MG', 'Nina Carla Bitencourt Aguilar', NULL, 'LUCAS WENDERSON DE SANDES PEREIRA', 15107, true, NOW()),
  ('LUIS GUSTAVO DE SOUZA CARVALHO', 'luis.carvalho@positivo.com.br', '5531995335621', 'MG', 'Nina Carla Bitencourt Aguilar', NULL, 'LUIS GUSTAVO DE SOUZA CARVALHO', 15108, true, NOW()),
  ('LUIZ FELIPE COELHO DE OLIVEIRA', 'luiz.oliveira@positivo.com.br', '5531999162026', 'MG', 'Nina Carla Bitencourt Aguilar', NULL, 'LUIZ FELIPE COELHO DE OLIVEIRA', 15114, true, NOW()),
  ('MARCOS DIAS DE SALES', 'marcos.sales@positivo.com.br', '5534999480059', 'MG', 'Nina Carla Bitencourt Aguilar', NULL, 'MARCOS DIAS DE SALES', 15975, true, NOW()),
  ('MATHEUS HENRIQUE RIBEIRO DE SOUZA', NULL, NULL, 'MG', 'Nina Carla Bitencourt Aguilar', NULL, 'MATHEUS HENRIQUE RIBEIRO DE SOUZA', 15876, true, NOW()),
  ('ONYALAN SILVA ALMEIDA', 'onyalan.almeida@positivo.com.br', '5591991976368', 'MG', 'Nina Carla Bitencourt Aguilar', NULL, 'ONYALAN SILVA ALMEIDA', 15504, true, NOW()),
  ('PABLO LUCAS DE MELO SILVA', 'pablo.silva@positivo.com.br', '5534984079841', 'MG', 'Nina Carla Bitencourt Aguilar', NULL, 'PABLO LUCAS DE MELO SILVA', 15115, true, NOW()),
  ('PAULO VICTOR ANDRADE MOTA VAZ', 'paulov@positivo.com.br', '5531995039532', 'MG', 'Nina Carla Bitencourt Aguilar', NULL, 'PAULO VICTOR ANDRADE MOTA VAZ', 16850, true, NOW()),
  ('RAQUEL DE OLIVEIRA MORATO', 'raquel.morato@positivo.com.br', '5531997519715', 'MG', 'Nina Carla Bitencourt Aguilar', NULL, 'RAQUEL DE OLIVEIRA MORATO', 11936, true, NOW()),
  ('RENATO MARCOS DE SOUZA', 'renato.souza@positivo.com.br', '5531984093124', 'MG', 'Nina Carla Bitencourt Aguilar', NULL, 'RENATO MARCOS DE SOUZA', 15117, true, NOW()),
  ('RICARDO OLIVERIA LIMA', 'ricardol@positivo.com.br', '5538998350626', 'MG', 'Nina Carla Bitencourt Aguilar', NULL, 'RICARDO OLIVERIA LIMA', 11656, true, NOW()),
  ('SERGIO HENRIQUE BRAGA RIBEIRO', 'sergio.ribeiro@positivo.com.br', '5535998892729', 'MG', 'Nina Carla Bitencourt Aguilar', NULL, 'SERGIO HENRIQUE BRAGA RIBEIRO', 15119, true, NOW()),
  ('THIAGO ARAUJO DE FARIA', 'thiago.faria@positivo.com.br', '5511942861924', 'MG', 'Nina Carla Bitencourt Aguilar', NULL, 'THIAGO ARAUJO DE FARIA', 15120, true, NOW()),
  ('THIAGO PEREIRA DE CASTRO', 'thiago.castro@positivo.com.br', NULL, 'MG', 'Nina Carla Bitencourt Aguilar', NULL, 'THIAGO PEREIRA DE CASTRO', 15631, true, NOW()),
  ('VINICIUS MENEZES GOMES', 'vinicius.gomes@positivo.com.br', '5531992691176', 'MG', 'Nina Carla Bitencourt Aguilar', NULL, 'VINICIUS MENEZES GOMES', 15351, true, NOW()),
  ('VITOR PEREIRA ADRIANO', 'vitorp@positivo.com.br', '5531996489903', 'MG', 'Nina Carla Bitencourt Aguilar', NULL, 'VITOR PEREIRA ADRIANO', 16358, true, NOW()),
  ('LUISA DIAS SPIRITO', 'LUISAD@POSITIVO.COM.BR', '5531995799089', 'MG', 'Nina Carla Bitencourt Aguilar', NULL, 'LUISA DIAS SPIRITO', 17673, true, NOW()),
  ('MARCOS POTROS GUILARDUCCI', 'MARCOS.GUILARDUCCI@POSITIVO.COM.BR', '5531999427680', 'MG', 'Nina Carla Bitencourt Aguilar', NULL, 'MARCOS POTROS GUILARDUCCI', 15741, true, NOW()),
  ('RICARDO OLIVEIRA LIMA', 'RICARDOL@POSITIVO.COM.BR', '5538998350626', 'MG', 'Nina Carla Bitencourt Aguilar', NULL, 'RICARDO OLIVEIRA LIMA', 15118, true, NOW()),
  ('WILLIAM LUCAS DE OLIVEIRA', 'williamo@positivo.com.br', NULL, 'MG', 'Nina Carla Bitencourt Aguilar', NULL, 'WILLIAM LUCAS DE OLIVEIRA', 17620, true, NOW()),
  ('JAIRO EDUARDO LOPES LANDIM', 'jairoe@positivo.com.br', '5565992129736', 'MT', 'Deyvson Leopoldino Da Silva', NULL, 'JAIRO EDUARDO LOPES LANDIM', 16629, true, NOW()),
  ('WANDERSON DOS SANTOS GONCALVES', 'WANDERSON.GONCALVES@POSITIVO.COM.BR', '5565999599455', 'MT', 'Deyvson Leopoldino Da Silva', NULL, 'WANDERSON DOS SANTOS GONCALVES', 16659, true, NOW()),
  ('NICIAS FREDERICO LONDON GOMES DA SILVA', 'NICIASS@POSITIVO.COM.BR', '556697264495', 'MT', 'Deyvson Leopoldino Da Silva', NULL, 'NICIAS FREDERICO LONDON GOMES DA SILVA', 17496, true, NOW()),
  ('CARLOS HENRIQUE ALVES OLIVEIRA MACAIBA DE SOUSA', 'carlosh@positivo.com.br', NULL, 'PB', 'Deyvson Leopoldino Da Silva', NULL, 'CARLOS HENRIQUE ALVES OLIVEIRA MACAIBA DE SOUSA', 15455, true, NOW()),
  ('CHARLES PEREIRA DANTAS', 'charles.dantas@positivo.com.br', '5582981455136', 'PB', 'Deyvson Leopoldino Da Silva', NULL, 'CHARLES PEREIRA DANTAS', 16713, true, NOW()),
  ('PEDRO MARTINIANO PEREIRA', 'pmartiniano@positivo.com.br', '5541991882728', 'PB', 'Deyvson Leopoldino Da Silva', NULL, 'PEDRO MARTINIANO PEREIRA', 15593, true, NOW()),
  ('VANDEBERGER EUSTAQUILINO PEREIRA DE SOUZA', 'vandebergere@positivo.com.br', '5583981958638', 'PB', 'Deyvson Leopoldino Da Silva', NULL, 'VANDEBERGER EUSTAQUILINO PEREIRA DE SOUZA', 17344, true, NOW()),
  ('DAVI ANDERSON COSTA DOS SANTOS', 'DAVI.SANTOS@POSITIVO.COM.BR', NULL, 'PB', 'Deyvson Leopoldino Da Silva', NULL, 'DAVI ANDERSON COSTA DOS SANTOS', 15188, true, NOW()),
  ('JORGE HENRIQUE FERNANDES NUNES', 'JNUNES@POSITIVO.COM.BR', '5541992907230', 'PB', 'Deyvson Leopoldino Da Silva', NULL, 'JORGE HENRIQUE FERNANDES NUNES', 16951, true, NOW()),
  ('EDILSON CARLOS DE SA NEVES', 'edilsonc@positivo.com.br', '5587996364060', 'PE', 'Deyvson Leopoldino Da Silva', NULL, 'EDILSON CARLOS DE SA NEVES', 15654, true, NOW()),
  ('EDUARDO LUIZ DE OLIVEIRA DIAS', 'eduardod@positivo.com.br', '5541991683868', 'PE', 'Deyvson Leopoldino Da Silva', NULL, 'EDUARDO LUIZ DE OLIVEIRA DIAS', 15461, true, NOW()),
  ('EDUARDO LUIZ MORAES DA COSTA', 'eduardoc@positivo.com.br', '5581999436600', 'PE', 'Deyvson Leopoldino Da Silva', NULL, 'EDUARDO LUIZ MORAES DA COSTA', 13057, true, NOW()),
  ('JADSON FERREIRA NEVES', 'jadsonf@positivo.com.br', '5541992163876', 'PE', 'Deyvson Leopoldino Da Silva', NULL, 'JADSON FERREIRA NEVES', 15978, true, NOW()),
  ('JOHNSON PESSOA SILVA', 'johnsons@positivo.com.br', '5511950791506', 'PE', 'Deyvson Leopoldino Da Silva', NULL, 'JOHNSON PESSOA SILVA', 16640, true, NOW()),
  ('JONATHAN FELIPE AVELINO ANDRE GOMES WAVRIK', 'jonathan.wavr@positivo.com.br', '5541992317503', 'PE', 'Deyvson Leopoldino Da Silva', NULL, 'JONATHAN FELIPE AVELINO ANDRE GOMES WAVRIK', 15465, true, NOW()),
  ('KAIO KORION SOARES ACCIOLY LINS', 'kaiok@positivo.com.br', NULL, 'PE', 'Deyvson Leopoldino Da Silva', NULL, 'KAIO KORION SOARES ACCIOLY LINS', 15463, true, NOW()),
  ('MARCIO ANDRÉ RODRIGUES SOUZA', NULL, NULL, 'PE', 'Deyvson Leopoldino Da Silva', NULL, 'MARCIO ANDRÉ RODRIGUES SOUZA', 15185, true, NOW()),
  ('ROBSON NEGROMONTE VASCONCELOS', 'rvasconcelos@positivo.com.br', '5541991064217', 'PE', 'Deyvson Leopoldino Da Silva', NULL, 'ROBSON NEGROMONTE VASCONCELOS', 15464, true, NOW()),
  ('THIAGO RODRIGO DE AQUINO', 'thiago.aquino@positivo.com.br', '5587999803395', 'PE', 'Deyvson Leopoldino Da Silva', NULL, 'THIAGO RODRIGO DE AQUINO', 17050, true, NOW()),
  ('FERNANDO ANTONIO DE ALMEIDA LIMA', 'FERNANDO.LIMA@POSITIVO.COM.BR', '554191364085', 'PE', 'Deyvson Leopoldino Da Silva', NULL, 'FERNANDO ANTONIO DE ALMEIDA LIMA', 17459, true, NOW()),
  ('JOSE HENRIQUE DA SILVA RAMOS', 'JOSER@POSITIVO.COM.BR', '5569999377304', 'PE', 'Deyvson Leopoldino Da Silva', NULL, 'JOSE HENRIQUE DA SILVA RAMOS', 16581, true, NOW()),
  ('CHARLES ADRIANO HACK', 'charlesh@positivo.com.br', NULL, 'PR', 'Cleandro De Souza Rocha', NULL, 'CHARLES ADRIANO HACK', 12003, true, NOW()),
  ('CLEIDE M DOS SANTOS', 'cleides@positivo.com.br', NULL, 'PR', 'Cleandro De Souza Rocha', NULL, 'CLEIDE M DOS SANTOS', 10919, true, NOW()),
  ('DANIEL JOSE BISPO', 'daniel.bispo@positivo.com.br', NULL, 'PR', 'Cleandro De Souza Rocha', NULL, 'DANIEL JOSE BISPO', 15259, true, NOW()),
  ('GABRIEL LEONARDO ZIMMERMANN ALVES', 'gabriel.alves@positivo.com.br', NULL, 'PR', 'Cleandro De Souza Rocha', NULL, 'GABRIEL LEONARDO ZIMMERMANN ALVES', 16095, true, NOW()),
  ('JONAS FILIPE DO NASCIMENTO SILVA', NULL, NULL, 'PR', 'Cleandro De Souza Rocha', NULL, 'JONAS FILIPE DO NASCIMENTO SILVA', 11457, true, NOW()),
  ('MARCOS RODRIGUES', 'mrodrigues@positivo.com.br', NULL, 'PR', 'Cleandro De Souza Rocha', NULL, 'MARCOS RODRIGUES', 14533, true, NOW()),
  ('RODRIGO RODRIGUES', 'rrodrigues@positivo.com.br', NULL, 'PR', 'Cleandro De Souza Rocha', NULL, 'RODRIGO RODRIGUES', 10927, true, NOW()),
  ('VINICIUS EDUARDO FIOR SCARPETA', 'vinicius.scarpeta@positivo.com.br', NULL, 'PR', 'Cleandro De Souza Rocha', NULL, 'VINICIUS EDUARDO FIOR SCARPETA', 16306, true, NOW()),
  ('AMAURY DE FREITAS GOMES', 'amauryf@positivo.com.br', '5541991058337', 'PR', 'Everton Renato Schendroski Bulhessich', NULL, 'AMAURY DE FREITAS GOMES', 16017, true, NOW()),
  ('BRUNNO NICOLAS DE MATTOS', 'brunno.mattos@positivo.com.br', NULL, 'PR', 'Everton Renato Schendroski Bulhessich', NULL, 'BRUNNO NICOLAS DE MATTOS', 17177, true, NOW()),
  ('DANIEL GARCIA', 'daniel.garcia@positivo.com.br', '5541991164823', 'PR', 'Everton Renato Schendroski Bulhessich', NULL, 'DANIEL GARCIA', 15764, true, NOW()),
  ('FERNANDO YUTAKA ITO', NULL, NULL, 'PR', 'Everton Renato Schendroski Bulhessich', NULL, 'FERNANDO YUTAKA ITO', 14975, true, NOW()),
  ('GUILHERME DE OLIVEIRA SOUZA', 'guilhermeos@positivo.com.br', '5541992806526', 'PR', 'Everton Renato Schendroski Bulhessich', NULL, 'GUILHERME DE OLIVEIRA SOUZA', 14966, true, NOW()),
  ('HAMILTON ALEXANDRINO DOS SANTOS', 'hsantos@positivo.com.br', '5541991950238', 'PR', 'Everton Renato Schendroski Bulhessich', NULL, 'HAMILTON ALEXANDRINO DOS SANTOS', 14967, true, NOW()),
  ('JAILSON DOS SANTOS', 'jailson.santos@positivo.com.br', NULL, 'PR', 'Everton Renato Schendroski Bulhessich', NULL, 'JAILSON DOS SANTOS', 16340, true, NOW()),
  ('LUCAS DE OLIVEIRA TEIXEIRA', 'lucaso@positivo.com.br', '5592994074406', 'PR', 'Everton Renato Schendroski Bulhessich', NULL, 'LUCAS DE OLIVEIRA TEIXEIRA', 16331, true, NOW()),
  ('LUCIANO DIAS DA SILVA', 'lucianod@positivo.com.br', '5541991093441', 'PR', 'Everton Renato Schendroski Bulhessich', NULL, 'LUCIANO DIAS DA SILVA', 14968, true, NOW()),
  ('MARCELO DE SOUZA MACHADO', 'mmachado@positivo.com.br', '5541991866901', 'PR', 'Everton Renato Schendroski Bulhessich', NULL, 'MARCELO DE SOUZA MACHADO', 12977, true, NOW()),
  ('MARCIO ROBERTO GARBUIO', NULL, NULL, 'PR', 'Everton Renato Schendroski Bulhessich', NULL, 'MARCIO ROBERTO GARBUIO', 13131, true, NOW()),
  ('NEI DE LIMA', 'nei.lima@positivo.com.br', '5541999538533', 'PR', 'Everton Renato Schendroski Bulhessich', NULL, 'NEI DE LIMA', 15918, true, NOW()),
  ('RODRIGO PINHEIRO MARTINS', 'rmartins@positivo.com.br', '5541991360895', 'PR', 'Everton Renato Schendroski Bulhessich', NULL, 'RODRIGO PINHEIRO MARTINS', 12589, true, NOW()),
  ('ROSELIO JANTARA', 'rjantara@positivo.com.br', '5541991474436', 'PR', 'Everton Renato Schendroski Bulhessich', NULL, 'ROSELIO JANTARA', 14972, true, NOW()),
  ('RYAN GABRIEL SKALECKI MARQUES', 'ryang@positivo.com.br', '5541991577161', 'PR', 'Everton Renato Schendroski Bulhessich', NULL, 'RYAN GABRIEL SKALECKI MARQUES', 14573, true, NOW()),
  ('WESLEY GONÇALVES DE OLIVEIRA DA SILVA', 'wesley.silva@positivo.com.br', '5541998127447', 'PR', 'Everton Renato Schendroski Bulhessich', NULL, 'WESLEY GONÇALVES DE OLIVEIRA DA SILVA', 15347, true, NOW()),
  ('JEAN FRANCISCO MIGUEL DE ANDRADE', 'JEAN.ANDRADE@POSITIVO.COM.BR', '554191023509', 'PR', 'Everton Renato Schendroski Bulhessich', NULL, 'JEAN FRANCISCO MIGUEL DE ANDRADE', 17300, true, NOW()),
  ('ADRIANO DE CARVALHO MACHADO', NULL, NULL, 'RJ', 'Alessandro Detrano Da Silva', NULL, 'ADRIANO DE CARVALHO MACHADO', 12591, true, NOW()),
  ('ANTÔNIO CARLOS LEITE DA SILVA', 'acarlos@positivo.com.br', '5521990639002', 'RJ', 'Alessandro Detrano Da Silva', NULL, 'ANTÔNIO CARLOS LEITE DA SILVA', 15664, true, NOW()),
  ('EDUARDO TOLC POLITI', NULL, NULL, 'RJ', 'Alessandro Detrano Da Silva', NULL, 'EDUARDO TOLC POLITI', 12757, true, NOW()),
  ('MAGNO ALEXANDRE DA SILVA', NULL, NULL, 'RJ', 'Alessandro Detrano Da Silva', NULL, 'MAGNO ALEXANDRE DA SILVA', 11111, true, NOW()),
  ('MARCELO LADI DE LIMA', 'mladi@positivo.com.br', '5521996796921', 'RJ', 'Alessandro Detrano Da Silva', NULL, 'MARCELO LADI DE LIMA', 12093, true, NOW()),
  ('MARCIO DA SILVA EDUARDO', 'marcioe@positivo.com.br', '5521998276598', 'RJ', 'Alessandro Detrano Da Silva', NULL, 'MARCIO DA SILVA EDUARDO', 13973, true, NOW()),
  ('MARCIO LUIS PEREIRA DOS SANTOS', 'marciol@positivo.com.br', '5521996435752', 'RJ', 'Alessandro Detrano Da Silva', NULL, 'MARCIO LUIS PEREIRA DOS SANTOS', 16252, true, NOW()),
  ('ROBSON DA SILVA CASTRO', 'robsons@positivo.com.br', '5541992289621', 'RJ', 'Alessandro Detrano Da Silva', NULL, 'ROBSON DA SILVA CASTRO', 12585, true, NOW()),
  ('VALERIA BARBOSA MONTEZUMA', 'vanessa.silva@positivo.com.br', '5521996435894', 'RJ', 'Alessandro Detrano Da Silva', NULL, 'VALERIA BARBOSA MONTEZUMA', 15972, true, NOW()),
  ('WILLIAM EDUARDO ABREU DE SANT ANNA', 'william.anna@positivo.com.br', '5541991692758', 'RJ', 'Alessandro Detrano Da Silva', NULL, 'WILLIAM EDUARDO ABREU DE SANT ANNA', 16635, true, NOW()),
  ('HUGO LEONARDO DA SILVA RODRIGUES', 'HUGOL@POSITIVO.COM.BR', '554192414327', 'RJ', 'Alessandro Detrano Da Silva', NULL, 'HUGO LEONARDO DA SILVA RODRIGUES', 17303, true, NOW()),
  ('CLEISON LIMA DA SILVA', 'CLEISONS@POSITIVO.COM.BR', '5521972009516', 'RJ', 'Alessandro Detrano Da Silva', NULL, 'CLEISON LIMA DA SILVA', 11535, true, NOW()),
  ('JULIANA LIMA DA COSTA', 'JULIANA.LIMA@POSITIVO.COM.BR', '5521996295713', 'RJ', 'Alessandro Detrano Da Silva', NULL, 'JULIANA LIMA DA COSTA', 11490, true, NOW()),
  ('LUIZ CLAUDIO DE OLIVEIRA LESSA', 'luizl@positivo.com.br', '5584988647404', 'RN', 'Deyvson Leopoldino Da Silva', NULL, 'LUIZ CLAUDIO DE OLIVEIRA LESSA', 15865, true, NOW()),
  ('MUNIZ ALBINO DA SILVA FILHO', 'munizf@positivo.com.br', NULL, 'RN', 'Deyvson Leopoldino Da Silva', NULL, 'MUNIZ ALBINO DA SILVA FILHO', 17095, true, NOW()),
  ('DHIONE PABULO', 'dhiones@positivo.com.br', '5541991879226', 'RO', 'Jorge Henrique Fernandes Nunes', NULL, 'DHIONE PABULO', 15003, true, NOW()),
  ('ERICLES GOMES DE ARAUJO', NULL, NULL, 'RO', 'Jorge Henrique Fernandes Nunes', NULL, 'ERICLES GOMES DE ARAUJO', 14042, true, NOW()),
  ('GEOVANE NOLASCO BIZERRA', 'geovane.bizerra@positivo.com.br', '5541992488680', 'RO', 'Jorge Henrique Fernandes Nunes', NULL, 'GEOVANE NOLASCO BIZERRA', 16145, true, NOW()),
  ('LUIS JACARANDA', 'luis.jacaranda@positivo.com.br', '5569993377257', 'RO', 'Jorge Henrique Fernandes Nunes', NULL, 'LUIS JACARANDA', 14815, true, NOW()),
  ('DHIONE PABULO ALVES DOS SANTOS', 'DHIONES@POSITIVO.COM.BR', '5541991879226', 'RO', 'Jorge Henrique Fernandes Nunes', NULL, 'DHIONE PABULO ALVES DOS SANTOS', 13526, true, NOW()),
  ('FABIO CEZIMBRA RUBO', 'fabioc@positivo.com.br', NULL, 'RS', 'Everton Renato Schendroski Bulhessich', NULL, 'FABIO CEZIMBRA RUBO', 12216, true, NOW()),
  ('FILIPE DE LIMA NUNES', 'filipe.nunes@positivo.com.br', '5553997031399', 'RS', 'Everton Renato Schendroski Bulhessich', NULL, 'FILIPE DE LIMA NUNES', 15509, true, NOW()),
  ('GUILHERME DE MATOS PAIVA', 'guilherme.paiva@positivo.com.br', '5548988644663', 'RS', 'Everton Renato Schendroski Bulhessich', NULL, 'GUILHERME DE MATOS PAIVA', 15599, true, NOW()),
  ('IAGNER RUVIARO CARDOSO', 'iagner.cardoso@positivo.com.br', NULL, 'RS', 'Everton Renato Schendroski Bulhessich', NULL, 'IAGNER RUVIARO CARDOSO', 17179, true, NOW()),
  ('LEONARD NUCCI DE OLIVEIRA', NULL, NULL, 'RS', 'Everton Renato Schendroski Bulhessich', NULL, 'LEONARD NUCCI DE OLIVEIRA', 15343, true, NOW()),
  ('LEONARDO GOMES MONTEIRO MIGUEIS CERQUEIRA', '-', NULL, 'RS', 'Everton Renato Schendroski Bulhessich', NULL, 'LEONARDO GOMES MONTEIRO MIGUEIS CERQUEIRA', 15479, true, NOW()),
  ('LILIAN FURTADO FIGUEIRA', NULL, NULL, 'RS', 'Everton Renato Schendroski Bulhessich', NULL, 'LILIAN FURTADO FIGUEIRA', 13826, true, NOW()),
  ('LUIZ FELIPE PEDROSO DA SILVA', 'luizs@positivo.com.br', '5541992054675', 'RS', 'Everton Renato Schendroski Bulhessich', NULL, 'LUIZ FELIPE PEDROSO DA SILVA', 13052, true, NOW()),
  ('MARCELO VARGAS DA SILVA JUNIOR', NULL, NULL, 'RS', 'Everton Renato Schendroski Bulhessich', NULL, 'MARCELO VARGAS DA SILVA JUNIOR', 9351, true, NOW()),
  ('PAULO CEZAR DA ROSA FILHO', 'pcezar@positivo.com.br', '5551991826141', 'RS', 'Everton Renato Schendroski Bulhessich', NULL, 'PAULO CEZAR DA ROSA FILHO', 15719, true, NOW()),
  ('RAFAEL SILVA DA SILVA', 'rafaelss@positivo.com.br', '5551992434424', 'RS', 'Everton Renato Schendroski Bulhessich', NULL, 'RAFAEL SILVA DA SILVA', 16117, true, NOW()),
  ('RODOLFO DE OLIVEIRA VICENTE', '-', NULL, 'RS', 'Everton Renato Schendroski Bulhessich', NULL, 'RODOLFO DE OLIVEIRA VICENTE', 15520, true, NOW()),
  ('VAGNER SILVA RESER', '-', NULL, 'RS', 'Everton Renato Schendroski Bulhessich', NULL, 'VAGNER SILVA RESER', 15785, true, NOW()),
  ('VINICIUS ESTEVAO LIMA PINTO', NULL, NULL, 'RS', 'Everton Renato Schendroski Bulhessich', NULL, 'VINICIUS ESTEVAO LIMA PINTO', 17018, true, NOW()),
  ('WESLEN BACCHI', NULL, NULL, 'RS', 'Everton Renato Schendroski Bulhessich', NULL, 'WESLEN BACCHI', 13088, true, NOW()),
  ('VITOR RAPHAEL NELSON SANTOS', 'LNELSON@POSITIVO.COM.BR', NULL, 'RS', 'Everton Renato Schendroski Bulhessich', NULL, 'VITOR RAPHAEL NELSON SANTOS', 17479, true, NOW()),
  ('ADRIANO FERREIRA BEZERRA', 'adrianof@positivo.com.br', NULL, 'SC', 'Everton Renato Schendroski Bulhessich', NULL, 'ADRIANO FERREIRA BEZERRA', 17675, true, NOW()),
  ('BRUNO DE ANHAIA MILER', 'bruno.miler@positivo.com.br', '5541991658018', 'SC', 'Everton Renato Schendroski Bulhessich', NULL, 'BRUNO DE ANHAIA MILER', 17637, true, NOW()),
  ('BRUNO GOMES KRAETZIG', 'brunok@positivo.com.br', '5541991529263', 'SC', 'Everton Renato Schendroski Bulhessich', NULL, 'BRUNO GOMES KRAETZIG', 17354, true, NOW()),
  ('CALONE RODRIGUES HALENSA', '-', NULL, 'SC', 'Everton Renato Schendroski Bulhessich', NULL, 'CALONE RODRIGUES HALENSA', 15774, true, NOW()),
  ('DIEGO CLAUDELER FRANCISCO', 'diegoc@positivo.com.br', '5541991866901', 'SC', 'Everton Renato Schendroski Bulhessich', NULL, 'DIEGO CLAUDELER FRANCISCO', 17355, true, NOW()),
  ('EMERSON FRANCA DE SOUZA', 'emerson.souza@positivo.com.br', '5541991229128', 'SC', 'Everton Renato Schendroski Bulhessich', NULL, 'EMERSON FRANCA DE SOUZA', 17065, true, NOW()),
  ('JAISON SALVADOR', NULL, NULL, 'SC', 'Everton Renato Schendroski Bulhessich', NULL, 'JAISON SALVADOR', 14731, true, NOW()),
  ('JONATHAN RABELO COSTA', '-', NULL, 'SC', 'Everton Renato Schendroski Bulhessich', NULL, 'JONATHAN RABELO COSTA', 14662, true, NOW()),
  ('JORGE LUIZ BENETTI', NULL, NULL, 'SC', 'Everton Renato Schendroski Bulhessich', NULL, 'JORGE LUIZ BENETTI', 17123, true, NOW()),
  ('LEANDRO DE SOUZA OLIVEIRA', 'leandro.oliveira@positivo.com.br', '5551995210567', 'SC', 'Everton Renato Schendroski Bulhessich', NULL, 'LEANDRO DE SOUZA OLIVEIRA', 17378, true, NOW()),
  ('LEONARDO DOS SANTOS', 'lssantos@positivo.com.br', '5541992791762', 'SC', 'Everton Renato Schendroski Bulhessich', NULL, 'LEONARDO DOS SANTOS', 17641, true, NOW()),
  ('LUIZ FELIPE SARTOR GÓES', '-', NULL, 'SC', 'Everton Renato Schendroski Bulhessich', NULL, 'LUIZ FELIPE SARTOR GÓES', 15776, true, NOW()),
  ('PAULO ROBERTO MARCON', '-', NULL, 'SC', 'Everton Renato Schendroski Bulhessich', NULL, 'PAULO ROBERTO MARCON', 14665, true, NOW()),
  ('PETERSON DIEGO DA MOTA RAMOS', NULL, NULL, 'SC', 'Maroe Kao Da Silva', NULL, 'PETERSON DIEGO DA MOTA RAMOS', 16206, true, NOW()),
  ('ABRAAO LINCOLN FONSECA', 'abraaolfonseca@gmail.com', '5517981455266', 'SP', 'Thiago Cardoso da Silva', NULL, 'ABRAAO LINCOLN FONSECA', 17001, true, NOW()),
  ('ADEMIR BORGES DE SOUZA JUNIOR', 'ademirj@positivo.com.br', '5511992872477', 'SP', 'Thiago Cardoso da Silva', NULL, 'ADEMIR BORGES DE SOUZA JUNIOR', 14495, true, NOW()),
  ('ADEMIR PEREIRA DA SILVA', 'ademir.silva@positivo.com.br', '5511981772280', 'SP', 'Adriano Luiz Cherubini Pompeo', NULL, 'ADEMIR PEREIRA DA SILVA', 16438, true, NOW()),
  ('ADRIANO CESAR RIBAS ZAFFALON', 'aczaffalon@gmail.com', '5511958039028', 'SP', 'Thiago Cardoso da Silva', NULL, 'ADRIANO CESAR RIBAS ZAFFALON', 16952, true, NOW()),
  ('ADRIEL FELIPE DA SILVA DE OLIVEIRA', 'adriel.oliveira@positivo.com.br', '5516981470361', 'SP', 'Thiago Cardoso da Silva', NULL, 'ADRIEL FELIPE DA SILVA DE OLIVEIRA', 16329, true, NOW()),
  ('ALESSANDRA DE FATIMA FERREIRA LOPES', 'alessandra.lopes@positivo.com.br', '5511975652115', 'SP', 'Adriano Luiz Cherubini Pompeo', NULL, 'ALESSANDRA DE FATIMA FERREIRA LOPES', 15328, true, NOW()),
  ('ALEX PEREIRA BASTOS', 'alex.bastos@positivo.com.br', '5511913990937', 'SP', 'Thiago Cardoso da Silva', NULL, 'ALEX PEREIRA BASTOS', 14599, true, NOW()),
  ('ALEXANDRE MATIAS CARVALHO LIMA', 'amatias@positivo.com.br', '5521991292498', 'SP', 'Thiago Cardoso da Silva', NULL, 'ALEXANDRE MATIAS CARVALHO LIMA', 16442, true, NOW()),
  ('ALFREDO SARETTA', 'asaretta450@gmail.com', '5516996098779', 'SP', 'Cristiane Aparecida De Almeida', NULL, 'ALFREDO SARETTA', 16957, true, NOW()),
  ('ALISSON MATOS DOS SANTOS', 'alisson.santos@positivo.com.br', '5511973725291', 'SP', 'Thiago Cardoso da Silva', NULL, 'ALISSON MATOS DOS SANTOS', 16874, true, NOW()),
  ('ANDERSON FARIAS VIEIRA', 'anderson.vieira@positivo.com.br', '5511994755078', 'SP', 'Adriano Luiz Cherubini Pompeo', NULL, 'ANDERSON FARIAS VIEIRA', 16147, true, NOW()),
  ('ANDRE PANIZZA DOS SANTOS', 'andre.santos@positivo.com.br', '5511941599047', 'SP', 'Adriano Luiz Cherubini Pompeo', NULL, 'ANDRE PANIZZA DOS SANTOS', 16476, true, NOW()),
  ('ANDRE QUEIROZ BARROS', 'andre.barros@positivo.com.br', '5511958511989', 'SP', 'Thiago Cardoso da Silva', NULL, 'ANDRE QUEIROZ BARROS', 16019, true, NOW()),
  ('ANTONIO FAGNER BASTOS DE SOUZA', 'antelitechnology@outlook.com', '5511916277847', 'SP', 'Leandro Monteiro Fernandes', NULL, 'ANTONIO FAGNER BASTOS DE SOUZA', 16995, true, NOW()),
  ('ANTONIO JOSE SALLUM ALOSTA FILHO', 'sallum@outlook.com.br', '5535996712228', 'SP', 'Thiago Cardoso da Silva', NULL, 'ANTONIO JOSE SALLUM ALOSTA FILHO', 16653, true, NOW()),
  ('ANTONIO RODRIGO SILVA GOMES DE OLIVEIRA', 'antonio.oliveira@positivo.com.br', '5511971377194', 'SP', 'Thiago Cardoso da Silva', NULL, 'ANTONIO RODRIGO SILVA GOMES DE OLIVEIRA', 16413, true, NOW()),
  ('BIANCA CRISTINA GOMES DA SILVA', 'bianca.eb0705@gmail.com', '5511957965718', 'SP', 'Adriano Luiz Cherubini Pompeo', NULL, 'BIANCA CRISTINA GOMES DA SILVA', 17024, true, NOW()),
  ('BRUNO CORREIA DE OLIVEIRA SILVA', 'bruno.co.silva@icloud.com', '5511971262255', 'SP', 'Adriano Luiz Cherubini Pompeo', NULL, 'BRUNO CORREIA DE OLIVEIRA SILVA', 16991, true, NOW()),
  ('BRUNO FERNANDES DE FREITAS', 'bruno.freitas@positivo.com.br', '5541992373450', 'SP', 'Adriano Luiz Cherubini Pompeo', NULL, 'BRUNO FERNANDES DE FREITAS', 14245, true, NOW()),
  ('BRUNO MAJORES RELA', 'bmajores@positivo.com.br', '5511951602665', 'SP', 'Thiago Cardoso da Silva', NULL, 'BRUNO MAJORES RELA', 12953, true, NOW()),
  ('BRUNO RAFAEL NASCIMENTO GONCALVES', 'brafael@positivo.com.br', '5519982727206', 'SP', 'Thiago Cardoso da Silva', NULL, 'BRUNO RAFAEL NASCIMENTO GONCALVES', 16243, true, NOW()),
  ('BRUNO RIBEIRO DE OLIVEIRA', 'brunotinf@gmail.com', '5514996233156', 'SP', 'Antonio Carlos Sant''anna', NULL, 'BRUNO RIBEIRO DE OLIVEIRA', 16036, true, NOW()),
  ('BRUNO WESLEY DA SILVA', 'bwesley@positivo.com.br', '5511961701054', 'SP', 'Leandro Monteiro Fernandes', NULL, 'BRUNO WESLEY DA SILVA', 16311, true, NOW()),
  ('CAIO CESAR OLIVEIRA DE SOUSA', 'caio.sousa@positivo.com.br', '5518997335553', 'SP', 'Thiago Cardoso da Silva', NULL, 'CAIO CESAR OLIVEIRA DE SOUSA', 16654, true, NOW()),
  ('CAIO SCARABEL FERREIRA', 'caio.ferreira@positivo.com.br', '5511985063679', 'SP', 'Adriano Luiz Cherubini Pompeo', NULL, 'CAIO SCARABEL FERREIRA', 16120, true, NOW()),
  ('CAIQUE RIBEIRO DOS SANTOS', 'Caique.r.santtos@gmail.com', '5511969467088', 'SP', 'Adriano Luiz Cherubini Pompeo', NULL, 'CAIQUE RIBEIRO DOS SANTOS', 16448, true, NOW()),
  ('CHARLES ROCHA LUZ', 'crocha@positivo.com.br', '5514998696491', 'SP', 'Thiago Cardoso da Silva', NULL, 'CHARLES ROCHA LUZ', 15361, true, NOW()),
  ('CLOVIS OUCHAR JUNIOR', 'CLOVIS OUCHAR JUNIOR', '5515991860596', 'SP', 'Thiago Cardoso da Silva', NULL, 'CLOVIS OUCHAR JUNIOR', 17023, true, NOW()),
  ('CRISTIAN LEANDRO DE JESUS', 'cristian.jesus@positivo.com.br', '5511947763905', 'SP', 'Adriano Luiz Cherubini Pompeo', NULL, 'CRISTIAN LEANDRO DE JESUS', 16383, true, NOW()),
  ('DANIEL DA SILVA ANDRADE', 'daniel.andrade@positivo.com.br', '5513991537517', 'SP', 'Leandro Monteiro Fernandes', NULL, 'DANIEL DA SILVA ANDRADE', 16859, true, NOW()),
  ('DANIEL TRIVELLATO PERINA', 'danielp@positivo.com.br', '5516996001985', 'SP', 'Thiago Cardoso da Silva', NULL, 'DANIEL TRIVELLATO PERINA', 16606, true, NOW()),
  ('DAVID HARISON DIAS DA SILVA', 'dharison@positivo.com.br', '5511933348495', 'SP', 'Thiago Cardoso da Silva', NULL, 'DAVID HARISON DIAS DA SILVA', 15993, true, NOW()),
  ('DIEGO DIAS FERREIRA', 'ddias@positivo.com.br', '5511963821270', 'SP', 'Thiago Cardoso da Silva', NULL, 'DIEGO DIAS FERREIRA', 11737, true, NOW()),
  ('DIEGO SANTANA NEGRAES BARBOZA', 'dsantana@positivo.com.br', '5511954334186', 'SP', 'Adriano Luiz Cherubini Pompeo', NULL, 'DIEGO SANTANA NEGRAES BARBOZA', 16517, true, NOW()),
  ('DINO MUTTI FORNIELIS LOPES', 'dino.lopes@positivo.com.br', '554192066105', 'SP', 'Adriano Luiz Cherubini Pompeo', NULL, 'DINO MUTTI FORNIELIS LOPES', 17595, true, NOW()),
  ('DIOGENES TADEU GRACIANO', 'diogenes.graciano@positivo.com.br', '5511998383862', 'SP', 'Adriano Luiz Cherubini Pompeo', NULL, 'DIOGENES TADEU GRACIANO', 16290, true, NOW()),
  ('DIOGO DE SOUZA CECCON', 'dsceccon@positivo.com.br', '5519991848868', 'SP', 'Thiago Cardoso da Silva', NULL, 'DIOGO DE SOUZA CECCON', 17112, true, NOW()),
  ('DOUGLAS OLIVEIRA SEVERIANO', 'douglas.severiano@positivo.com.br', '5511944467601', 'SP', 'Adriano Luiz Cherubini Pompeo', NULL, 'DOUGLAS OLIVEIRA SEVERIANO', 15680, true, NOW()),
  ('DOUGLAS VAZ DA SILVA', 'douglasvaz1987@gmail.com', '5511969519939', 'SP', 'Adriano Luiz Cherubini Pompeo', NULL, 'DOUGLAS VAZ DA SILVA', 15866, true, NOW()),
  ('EDGAR HENRIQUE NERY', 'edgar.nery@positivo.com.br', '5518981649832', 'SP', 'Joyce Gomes Rodrigues', NULL, 'EDGAR HENRIQUE NERY', 16350, true, NOW()),
  ('EDSON ALVES VALADAO FILHO', 'edson_valadao@yahoo.com.br', '5514997664901', 'SP', 'Thiago Cardoso da Silva', NULL, 'EDSON ALVES VALADAO FILHO', 17049, true, NOW()),
  ('EDUARDO ORTOLANI TURCO', 'eduardo.turco@positivo.com.br', '5516991031604', 'SP', 'Thiago Cardoso da Silva', NULL, 'EDUARDO ORTOLANI TURCO', 16934, true, NOW()),
  ('ELIAS RODRIGUES BOAVENTURA CUNHA', 'eliasc@positivo.com.br', '5515991345870', 'SP', 'Antonio Carlos Sant''anna', NULL, 'ELIAS RODRIGUES BOAVENTURA CUNHA', 17115, true, NOW()),
  ('ERICK WILLIAMS FERREIRA DA SILVA', 'erick.silva@positivo.com.br', '5513978182112', 'SP', 'Thiago Cardoso da Silva', NULL, 'ERICK WILLIAMS FERREIRA DA SILVA', 16339, true, NOW()),
  ('ERITON OLIVEIRA PINTO DA SILVA', 'eriton.silva@positivo.com.br', '5511969088430', 'SP', 'Thiago Cardoso da Silva', NULL, 'ERITON OLIVEIRA PINTO DA SILVA', 14190, true, NOW()),
  ('EULLER DOS SANTOS BATISTA', 'euller.batista@positivo.com.br', '5514997138818', 'SP', 'Thiago Cardoso da Silva', NULL, 'EULLER DOS SANTOS BATISTA', 16615, true, NOW()),
  ('EVERSON DA SILVA SOARES', 'everson.soares@positivo.com.br', '5511944565763', 'SP', 'Antonio Carlos Sant''anna', NULL, 'EVERSON DA SILVA SOARES', 15171, true, NOW()),
  ('FABRICIO FELIPE DOS SANTOS PINTO', 'fabriciof@positivo.com.br', '5512991787356', 'SP', 'Thiago Cardoso da Silva', NULL, 'FABRICIO FELIPE DOS SANTOS PINTO', 16689, true, NOW()),
  ('FERNANDO ALVES GALVAO', 'fernandoalvesgalvao11@gmail.com', '5511984271679', 'SP', 'Thiago Cardoso da Silva', NULL, 'FERNANDO ALVES GALVAO', 17085, true, NOW()),
  ('FERNANDO CAMPOS SOUZA', 'fernandos@positivo.com.br', '5511981448701', 'SP', 'Thiago Cardoso da Silva', NULL, 'FERNANDO CAMPOS SOUZA', 16703, true, NOW()),
  ('FERNANDO VIEIRA ALMEIDA', 'fernando.almeida@positivo.com.br', '5511961862787', 'SP', 'Adriano Luiz Cherubini Pompeo', NULL, 'FERNANDO VIEIRA ALMEIDA', 15407, true, NOW()),
  ('FILIPE MIORIN DE LIMA', 'filipe.lima@positivo.com.br', '5517996611903', 'SP', 'Cristiane Aparecida de Almeida', NULL, 'FILIPE MIORIN DE LIMA', 17116, true, NOW()),
  ('FILIPI DE ALMEIDA MAMONI', 'filipi.mamoni@positivo.com.br', '5511956822069', 'SP', 'Antonio Carlos Sant''anna', NULL, 'FILIPI DE ALMEIDA MAMONI', 14861, true, NOW()),
  ('GABRIEL AMORIM FOGACA DE SOUSA', 'gabrielfsousa123@gmail.com', '5515988288107', 'SP', 'Thiago Cardoso da Silva', NULL, 'GABRIEL AMORIM FOGACA DE SOUSA', 16631, true, NOW()),
  ('GABRIEL DE SOUZA NASCIMENTO', 'gnascimento@positivo.com.br', '5511985426606', 'SP', 'Adriano Luiz Cherubini Pompeo', NULL, 'GABRIEL DE SOUZA NASCIMENTO', 16361, true, NOW()),
  ('GABRIEL JUNQUEIRA LEITE', 'gabriel.leite@positivo.com.br', '5511982007780', 'SP', 'Adriano Luiz Cherubini Pompeo', NULL, 'GABRIEL JUNQUEIRA LEITE', 16420, true, NOW()),
  ('GABRIEL LEONARDO OLIVEIRA OZORIO', 'gabriel.ozorio@positivo.com.br', '5519994515435', 'SP', 'Antonio Carlos Sant''anna', NULL, 'GABRIEL LEONARDO OLIVEIRA OZORIO', 16688, true, NOW()),
  ('GABRIEL PAGLIA', 'gabriel.paglia@positivo.com.br', '5511964660726', 'SP', 'Thiago Cardoso da Silva', NULL, 'GABRIEL PAGLIA', 16292, true, NOW()),
  ('GABRIEL RENNAN DIAS PEREIRA', 'grennan@positivo.com.br', '5511968475220', 'SP', 'Adriano Luiz Cherubini Pompeo', NULL, 'GABRIEL RENNAN DIAS PEREIRA', 16146, true, NOW()),
  ('GABRIEL RIBEIRO', 'gabrib04@gmail.com', '5514997347526', 'SP', 'Thiago Cardoso da Silva', NULL, 'GABRIEL RIBEIRO', 17032, true, NOW()),
  ('GEILTON APARECIDO CLEMENTE', 'geiltonc@positivo.com.br', '5511994387078', 'SP', 'Adriano Luiz Cherubini Pompeo', NULL, 'GEILTON APARECIDO CLEMENTE', 16220, true, NOW()),
  ('GUILHERME AUGUSTO ALEXANDRE TORTELLI', 'guilherme_augusto_12@hotmail.com', '5516974018374', 'SP', 'Joyce Gomes Rodrigues', NULL, 'GUILHERME AUGUSTO ALEXANDRE TORTELLI', 15249, true, NOW()),
  ('GUILHERME DE ALMEIDA NOGUEIRA', 'guilherme.nogueira@positivo.com.br', '5514981349379', 'SP', 'Joyce Gomes Rodrigues', NULL, 'GUILHERME DE ALMEIDA NOGUEIRA', 15181, true, NOW()),
  ('GUILHERME DE CAMARGO TONETTO DOS REIS', 'guilherme.reis@positivo.com.br', '5516981318914', 'SP', 'Cristiane Aparecida De Almeida', NULL, 'GUILHERME DE CAMARGO TONETTO DOS REIS', 16665, true, NOW()),
  ('GUILHERME YUZO MIYASIRO UEHARA', 'guilherme.uehara@positivo.com.br', '5511961778242', 'SP', 'Adriano Luiz Cherubini Pompeo', NULL, 'GUILHERME YUZO MIYASIRO UEHARA', 15024, true, NOW()),
  ('GUSTAVO COLETO DA SILVA', 'gcoleto@positivo.com.br', '5511997428177', 'SP', 'Adriano Luiz Cherubini Pompeo', NULL, 'GUSTAVO COLETO DA SILVA', 16388, true, NOW()),
  ('GUSTAVO DE OLIVEIRA BOREL', 'gustavo.borel@positivo.com.br', '5511982230473', 'SP', 'Adriano Luiz Cherubini Pompeo', NULL, 'GUSTAVO DE OLIVEIRA BOREL', 16362, true, NOW()),
  ('GUSTAVO GALDINO MOREIRA', 'ggaldino@positivo.com.br', '5511968494222', 'SP', 'Leandro Monteiro Fernandes', NULL, 'GUSTAVO GALDINO MOREIRA', 16210, true, NOW()),
  ('GUSTAVO GUIMARAES COSTA SILVA', 'gustavo.silva@positivo.com.br', '5511954801217', 'SP', 'Adriano Luiz Cherubini Pompeo', NULL, 'GUSTAVO GUIMARAES COSTA SILVA', 12775, true, NOW()),
  ('HELENO MEIRA DOS SANTOS', 'gaibinasantos@gmail.com', '5515998107985', 'SP', 'Antonio Carlos Sant''anna', NULL, 'HELENO MEIRA DOS SANTOS', 15508, true, NOW()),
  ('HENRIQUE GALDINO DA SILVA', 'henriques@positivo.com.br', '5541992160811', 'SP', 'Adriano Luiz Cherubini Pompeo', NULL, 'HENRIQUE GALDINO DA SILVA', 14233, true, NOW()),
  ('HERBERT DE ALENCAR GUAREZI', 'herbertguarezi@gmail.com', '5511934081778', 'SP', 'Leandro Monteiro Fernandes', NULL, 'HERBERT DE ALENCAR GUAREZI', 15394, true, NOW()),
  ('IAN GARCIA DA COSTA', 'ian.costa@positivo.com.br', '5515991316559', 'SP', 'Antonio Carlos Sant''anna', NULL, 'IAN GARCIA DA COSTA', 16244, true, NOW()),
  ('IGOR IAGO DE SOUZA', 'igori@positivo.com.br', '5517981908818', 'SP', 'Antonio Carlos Sant''anna', NULL, 'IGOR IAGO DE SOUZA', 16890, true, NOW()),
  ('IZEQUIEL ISRAELITO DA SILVA', 'izequiel.silva@positivo.com.br', '5511912716896', 'SP', 'Antonio Carlos Sant''anna', NULL, 'IZEQUIEL ISRAELITO DA SILVA', 15154, true, NOW()),
  ('JACIANO SEBASTIAO DE OLIVEIRA', 'jaciano.oliveira@positivo.com.br', '5511982782245', 'SP', 'Adriano Luiz Cherubini Pompeo', NULL, 'JACIANO SEBASTIAO DE OLIVEIRA', 12810, true, NOW()),
  ('JAYME FUMAGALLI PRADO E SOUSA', 'jaymefps@gmail.com', '5519992940060', 'SP', 'Joyce Gomes Rodrigues', NULL, 'JAYME FUMAGALLI PRADO E SOUSA', 17043, true, NOW()),
  ('JEFERSON ARTUR VULCANIS', 'jeferson.vulcanis@positivo.com.br', '5519991259668', 'SP', 'Antonio Carlos Sant''anna', NULL, 'JEFERSON ARTUR VULCANIS', 15047, true, NOW()),
  ('JEFFERSON EDUARDO MOREIRA DA SILVA', 'jesilva@positivo.com.br', '5511995783469', 'SP', 'Thiago Cardoso da Silva', NULL, 'JEFFERSON EDUARDO MOREIRA DA SILVA', 16363, true, NOW()),
  ('JOABE DA SILVA VEIGA', 'joabesveiga@positivo.com.br', '5518991280768', 'SP', 'Thiago Cardoso da Silva', NULL, 'JOABE DA SILVA VEIGA', 16041, true, NOW()),
  ('JOAO CARLOS CASTRO DE LIMA', 'jlima@positivo.com.br', '5519981697636', 'SP', 'Cristiane Aparecida de Almeida', NULL, 'JOAO CARLOS CASTRO DE LIMA', 16125, true, NOW()),
  ('JOAO HENRIQUE RODRIGUES DE SOUZA', 'joaorsouza233@gmail.com', '5514991867807', 'SP', 'Joyce Gomes Rodrigues', NULL, 'JOAO HENRIQUE RODRIGUES DE SOUZA', 16694, true, NOW()),
  ('JOAO HENRIQUE SOARES NETO', 'joaon@positivo.com.br', '5511970737301', 'SP', 'Adriano Luiz Cherubini Pompeo', NULL, 'JOAO HENRIQUE SOARES NETO', 16171, true, NOW()),
  ('JOAO PAULO BASTOS', 'jbastos@positivo.com.br', '5514996882507', 'SP', 'Joyce Gomes Rodrigues', NULL, 'JOAO PAULO BASTOS', 16650, true, NOW()),
  ('JOAO PAULO DA SILVA RAFAEL', 'joao.rafael@positivo.com.br', '5511933915314', 'SP', 'Thiago Cardoso da Silva', NULL, 'JOAO PAULO DA SILVA RAFAEL', 12981, true, NOW()),
  ('JOEL CORREA JUNIOR', 'joel.junior@positivo.com.br', '5513997154891', 'SP', 'Leandro Monteiro Fernandes', NULL, 'JOEL CORREA JUNIOR', 16238, true, NOW()),
  ('JOSE HENRIQUE SEIXAS', 'Jhenriqueseixas@gmail.com', '5516974043137', 'SP', 'Thiago Cardoso da Silva', NULL, 'JOSE HENRIQUE SEIXAS', 17048, true, NOW()),
  ('JOSE MARLOS LOPES DA SILVA', 'bauru.bauru2016@gmail.com', '5514991242232', 'SP', 'Thiago Cardoso da Silva', NULL, 'JOSE MARLOS LOPES DA SILVA', 15213, true, NOW()),
  ('JUNIOR SANTOS GIGANTE VIANA', 'JUN.ARTE@HOTMAIL.COM', '5519988221723', 'SP', 'Thiago Cardoso da Silva', NULL, 'JUNIOR SANTOS GIGANTE VIANA', 16242, true, NOW()),
  ('KESLLEY PEREIRA DA SILVA', 'keslleyp@positivo.com.br', '5511978035324', 'SP', 'Adriano Luiz Cherubini Pompeo', NULL, 'KESLLEY PEREIRA DA SILVA', 16661, true, NOW()),
  ('KEVIN AGUIAR DOS SANTOS', 'kevin.santos@positivo.com.br', '5511999401032', 'SP', 'Thiago Cardoso da Silva', NULL, 'KEVIN AGUIAR DOS SANTOS', 17640, true, NOW()),
  ('LEANDRO DAUD COMAR', 'leandrodaud@outlook.com', '5517997362607', 'SP', 'Thiago Cardoso da Silva', NULL, 'LEANDRO DAUD COMAR', 15252, true, NOW()),
  ('LEONARDO DEMETRIO DA FONSECA', 'nexacoreautomacao@gmail.com', '5513996589629', 'SP', 'Leandro Monteiro Fernandes', NULL, 'LEONARDO DEMETRIO DA FONSECA', 17094, true, NOW()),
  ('LEONE HENRIQUE DA SILVA SANTOS', 'leone.henrik1995@gmail.com', '5511941886857', 'SP', 'Antonio Carlos Sant''anna', NULL, 'LEONE HENRIQUE DA SILVA SANTOS', 17014, true, NOW()),
  ('LUCAS CARVALHO PAIVA DA SILVA', 'lucasc@positivo.com.br', '5511971180954', 'SP', 'Thiago Cardoso da Silva', NULL, 'LUCAS CARVALHO PAIVA DA SILVA', 16167, true, NOW()),
  ('LUCAS DA SILVA FEITOSA', 'lucas.feitosa@positivo.com.br', '5511984796034', 'SP', 'Thiago Cardoso da Silva', NULL, 'LUCAS DA SILVA FEITOSA', 16657, true, NOW()),
  ('LUCAS EVANGELISTA AUGUSTO', 'lucas.augusto@positivo.com.br', '5511976387973', 'SP', 'Adriano Luiz Cherubini Pompeo', NULL, 'LUCAS EVANGELISTA AUGUSTO', 16122, true, NOW()),
  ('MARCELO FABIANO DO NASCIMENTO', 'marcelo.nascimento@positivo.com.br', '5511971294959', 'SP', 'Leandro Monteiro Fernandes', NULL, 'MARCELO FABIANO DO NASCIMENTO', 16583, true, NOW()),
  ('MARCIO SANTOS SANTANA', 'Plugmss@yahoo.com.br', '5579988138181', 'SP', 'Thiago Cardoso da Silva', NULL, 'MARCIO SANTOS SANTANA', 16651, true, NOW()),
  ('MARCUS PABLO GONGORA', 'marcusg@positivo.com.br', '5511934399693', 'SP', 'Antonio Carlos Sant''anna', NULL, 'MARCUS PABLO GONGORA', 14234, true, NOW()),
  ('MARINA ZORZELLI', 'marina.zorzelli@gmail.com', '5511994089806', 'SP', 'Adriano Luiz Cherubini Pompeo', NULL, 'MARINA ZORZELLI', 16994, true, NOW()),
  ('MARLON WASLLEY MENDES DA SILVA', 'marlonw@positivo.com.br', '5519992193429', 'SP', 'Thiago Cardoso da Silva', NULL, 'MARLON WASLLEY MENDES DA SILVA', 17114, true, NOW()),
  ('MATEUS FORTUNATO XAVIER', 'mateusx@positivo.com.br', '5511971258459', 'SP', 'Thiago Cardoso da Silva', NULL, 'MATEUS FORTUNATO XAVIER', 15295, true, NOW()),
  ('MATHEUS GUSTAVO LOURENCO DE GODOY', 'matheus.godoy@positivo.com.br', '5514997613367', 'SP', 'Antonio Carlos Sant''anna', NULL, 'MATHEUS GUSTAVO LOURENCO DE GODOY', 16931, true, NOW()),
  ('MATHEUS HENRIQUE ABREU DE FREITAS', 'matheus.freitas@positivo.com.br', '5514998277822', 'SP', 'Thiago Cardoso da Silva', NULL, 'MATHEUS HENRIQUE ABREU DE FREITAS', 16687, true, NOW()),
  ('MATHEUS VINICIUS SILVEIRA DE CAMPOS', 'matheus.campos@positivo.com.br', '5511977640584', 'SP', 'Adriano Luiz Cherubini Pompeo', NULL, 'MATHEUS VINICIUS SILVEIRA DE CAMPOS', 16404, true, NOW()),
  ('MAURICIO FERREIRA NOGUEIRA', 'mauricio.nogueira@positivo.com.br', '5513992070954', 'SP', 'Thiago Cardoso da Silva', NULL, 'MAURICIO FERREIRA NOGUEIRA', 14883, true, NOW()),
  ('MICHEL DA SILVA GOMES', 'michel.gomes@positivo.com.br', '5511958775151', 'SP', 'Adriano Luiz Cherubini Pompeo', NULL, 'MICHEL DA SILVA GOMES', 14511, true, NOW()),
  ('MICHEL NEVES LOBO', 'michel-lobo@hotmail.com', '5518997883247', 'SP', 'Joyce Gomes Rodrigues', NULL, 'MICHEL NEVES LOBO', 15989, true, NOW()),
  ('MOACIR SABINO DA SILVA', 'moacir.silva@positivo.com.br', '5513982319425', 'SP', 'Leandro Monteiro Fernandes', NULL, 'MOACIR SABINO DA SILVA', 15937, true, NOW()),
  ('NATANAEL CAMPOS CAMARGO JUNIOR', 'natanael.junior@outlook.com', '5514997868320', 'SP', 'Thiago Cardoso da Silva', NULL, 'NATANAEL CAMPOS CAMARGO JUNIOR', 17064, true, NOW()),
  ('NILTON CESAR DA SILVA LARANJA', 'lan.gamenet@hotmail.com', '5518997305220', 'SP', 'Thiago Cardoso da Silva', NULL, 'NILTON CESAR DA SILVA LARANJA', 15399, true, NOW()),
  ('PABLO MARCELO CLEMENTE DA SILVA', 'pablos@positivo.com.br', '5516982485683', 'SP', 'Cristiane Aparecida de Almeida', NULL, 'PABLO MARCELO CLEMENTE DA SILVA', 15388, true, NOW()),
  ('PAULO CESAR VITAL', 'pcesar@positivo.com.br', '5516997200984', 'SP', 'Thiago Cardoso da Silva', NULL, 'PAULO CESAR VITAL', 16639, true, NOW()),
  ('PAULO HENRIQUE SANTANA DE MELO', 'paulynholemon@gmail.com', '5561984959636', 'SP', 'Thiago Cardoso da Silva', NULL, 'PAULO HENRIQUE SANTANA DE MELO', 15822, true, NOW()),
  ('PAULO HENRIQUE SOUZA COSTA', 'paulo.costa@positivo.com.br', '5511953516764', 'SP', 'Thiago Cardoso da Silva', NULL, 'PAULO HENRIQUE SOUZA COSTA', 16982, true, NOW()),
  ('RAFAEL ALVES GUIMARAES', 'rafael.guimaraes@positivo.com.br', '5511942279217', 'SP', 'Adriano Luiz Cherubini Pompeo', NULL, 'RAFAEL ALVES GUIMARAES', 16369, true, NOW()),
  ('RAFAEL DE FREITAS SILVA MENEZES', 'rfreitas@positivo.com.br', '5515996836876', 'SP', 'Adriano Luiz Cherubini Pompeo', NULL, 'RAFAEL DE FREITAS SILVA MENEZES', 16506, true, NOW()),
  ('RAFAEL DE LIMA SANTANA', 'dev.rafaelsantana@gmail.com', '5515996836876', 'SP', 'Thiago Cardoso da Silva', NULL, 'RAFAEL DE LIMA SANTANA', 16658, true, NOW()),
  ('RAFAEL NUNES LAS CASAS NAVARRO', 'rafael.navarro@positivo.com.br', '5511939036048', 'SP', 'Adriano Luiz Cherubini Pompeo', NULL, 'RAFAEL NUNES LAS CASAS NAVARRO', 16870, true, NOW()),
  ('RAPHAEL ELIAS BARBOSA', 'raphael.barbosa@positivo.com.br', '5512987095571', 'SP', 'Thiago Cardoso da Silva', NULL, 'RAPHAEL ELIAS BARBOSA', 16035, true, NOW()),
  ('RAPHAEL LONDE SIMOES', 'raphael.simoes@positivo.com.br', '5511911048237', 'SP', 'Thiago Cardoso da Silva', NULL, 'RAPHAEL LONDE SIMOES', 16370, true, NOW()),
  ('RENATO NASCIMENTO SANTOS', 'renato.pronasa@gmail.com', '5515996080029', 'SP', 'Thiago Cardoso da Silva', NULL, 'RENATO NASCIMENTO SANTOS', 16037, true, NOW()),
  ('RICARDO APARECIDO BARRETO', 'ricardob@positivo.com.br', '5511994642736', 'SP', 'Thiago Cardoso da Silva', NULL, 'RICARDO APARECIDO BARRETO', 15297, true, NOW()),
  ('RICARDO ROCHA DE SOUZA', 'rrsouza@positivo.com.br', '5519999206187', 'SP', 'Antonio Carlos Sant''anna', NULL, 'RICARDO ROCHA DE SOUZA', 16188, true, NOW()),
  ('RICARDO VERONEZZI', 'ricardo.veronezzi@positivo.com.br', '5511941701597', 'SP', 'Adriano Luiz Cherubini Pompeo', NULL, 'RICARDO VERONEZZI', 16254, true, NOW()),
  ('RODRIGO PINHEIRO DE AZEVEDO', 'rpinheiro@positivo.com.br', '5511985280131', 'SP', 'Thiago Cardoso da Silva', NULL, 'RODRIGO PINHEIRO DE AZEVEDO', 16922, true, NOW()),
  ('RODRIGO RODRIGUES ALVES', 'rodrigorodriguesalves@gmail.com', '5511990192273', 'SP', 'Thiago Cardoso da Silva', NULL, 'RODRIGO RODRIGUES ALVES', 16371, true, NOW()),
  ('RODRIGO RUAS MORENO', 'rodrigo.moreno@positivo.com.br', '5513991914755', 'SP', 'Leandro Monteiro Fernandes', NULL, 'RODRIGO RUAS MORENO', 16414, true, NOW()),
  ('ROGERIO ARISTIDES DOS SANTOS', 'rarosinformatica@gmail.com', '5511993293105', 'SP', 'Adriano Luiz Cherubini Pompeo', NULL, 'ROGERIO ARISTIDES DOS SANTOS', 16887, true, NOW()),
  ('RONALDO CESPEDES', 'ronaldo.cespedes@positivo.com.br', '5514988211721', 'SP', 'Thiago Cardoso da Silva', NULL, 'RONALDO CESPEDES', 15726, true, NOW()),
  ('RONALDO CORREA', 'ronaldo.correa@positivo.com.br', '5512982472632', 'SP', 'Thiago Cardoso da Silva', NULL, 'RONALDO CORREA', 16686, true, NOW()),
  ('RONALDO UENO VALERIO', 'ronaldo.valerio@positivo.com.br', '5511933805724', 'SP', 'Adriano Luiz Cherubini Pompeo', NULL, 'RONALDO UENO VALERIO', 14509, true, NOW()),
  ('RUBENS JUNIO FERREIRA VITALINO', 'rubensjuniorfvitalino@gmail.com', '5511932127538', 'SP', 'Adriano Luiz Cherubini Pompeo', NULL, 'RUBENS JUNIO FERREIRA VITALINO', 15023, true, NOW()),
  ('SAMUEL LUCAS CARNEIRO CHAVES', 'samuel.chaves@positivo.com.br', '5512996180070', 'SP', 'Thiago Cardoso da Silva', NULL, 'SAMUEL LUCAS CARNEIRO CHAVES', 16591, true, NOW()),
  ('SAULO EMMANUEL DOS SANTOS BRITO', 'saulobrito0103@gmail.com', '5511971828498', 'SP', 'Thiago Cardoso da Silva', NULL, 'SAULO EMMANUEL DOS SANTOS BRITO', 17073, true, NOW()),
  ('SILAS DE ALVARENGA PRADO', 'silasprado.ti@gmail.com', '5512991822219', 'SP', 'Thiago Cardoso da Silva', NULL, 'SILAS DE ALVARENGA PRADO', 16704, true, NOW()),
  ('STEFANY BALBINO DIAS', 'stefanydias22@icloud.com', '5511974194525', 'SP', 'Adriano Luiz Cherubini Pompeo', NULL, 'STEFANY BALBINO DIAS', 17087, true, NOW()),
  ('STEFANY DIAS ROSSI', 'stefanydiasrossi@gmail.com', '5515991976744', 'SP', 'Antonio Carlos Sant''anna', NULL, 'STEFANY DIAS ROSSI', 16973, true, NOW()),
  ('THIAGO FERNANDO GOMES DE OLIVEIRA PINTO', 'tfernando@positivo.com.br', '5519983616080', 'SP', 'Antonio Carlos Sant''anna', NULL, 'THIAGO FERNANDO GOMES DE OLIVEIRA PINTO', 16283, true, NOW()),
  ('THIAGO REINALDO RODRIGUES', 'thiago.rodrigues@positivo.com.br', '5511976594785', 'SP', 'Adriano Luiz Cherubini Pompeo', NULL, 'THIAGO REINALDO RODRIGUES', 16518, true, NOW()),
  ('THOMAZ EDER DE SOUZA', 'thomaz.souza@positivo.com.br', '5518991153258', 'SP', 'Joyce Gomes Rodrigues', NULL, 'THOMAZ EDER DE SOUZA', 16230, true, NOW()),
  ('VAGNER DE SOUZA BARBOSA', 'vagner.agil@gmail.com', '5511977412918', 'SP', 'Antonio Carlos Sant''anna', NULL, 'VAGNER DE SOUZA BARBOSA', 16401, true, NOW()),
  ('VAGNER VIDAL', 'vagner.vidal@heartech.com.br', '5511947337939', 'SP', 'Adriano Luiz Cherubini Pompeo', NULL, 'VAGNER VIDAL', 16182, true, NOW()),
  ('VICTOR RYAN ZAGO LUJAN', 'victoryan.zago@outlook.com', '5518996104583', 'SP', 'Joyce Gomes Rodrigues', NULL, 'VICTOR RYAN ZAGO LUJAN', 17030, true, NOW()),
  ('VINICIUS DACIO DA SILVA', 'viniciusdacio@gmail.com', '554791924120', 'SP', 'Antonio Carlos Sant''anna', NULL, 'VINICIUS DACIO DA SILVA', 17028, true, NOW()),
  ('VINICIUS MUCIO', 'vmucio@positivo.com.br', '5511942128473', 'SP', 'Thiago Cardoso da Silva', NULL, 'VINICIUS MUCIO', 12993, true, NOW()),
  ('WANDERSON CRUZ SANTOS', 'wandersons@positivo.com.br', '5511946142894', 'SP', 'Adriano Luiz Cherubini Pompeo', NULL, 'WANDERSON CRUZ SANTOS', 16149, true, NOW()),
  ('WELLINGTON TRANQUITELLA DE MELO', 'wellington.melo@positivo.com.br', '5514991274528', 'SP', 'Thiago Cardoso da Silva', NULL, 'WELLINGTON TRANQUITELLA DE MELO', 16051, true, NOW()),
  ('WELLINGTON VICTOR TORRES', 'wellington.torres@positivo.com.br', '5511999529400', 'SP', 'Adriano Luiz Cherubini Pompeo', NULL, 'WELLINGTON VICTOR TORRES', 16101, true, NOW()),
  ('WESLEY MACHADO DA SILVA', 'wmachado@positivo.com.br', '5519992425190', 'SP', 'Antonio Carlos Sant''anna', NULL, 'WESLEY MACHADO DA SILVA', 17113, true, NOW()),
  ('WESLEY RODRIGUES RIBEIRO', 'wesley.ribeiro@positivo.com.br', '5517991371276', 'SP', 'Thiago Cardoso da Silva', NULL, 'WESLEY RODRIGUES RIBEIRO', 16112, true, NOW()),
  ('WESLEY SANTOS DA CUNHA', 'wesleycwnha@gmail.com', '5511962458414', 'SP', 'Adriano Luiz Cherubini Pompeo', NULL, 'WESLEY SANTOS DA CUNHA', 16882, true, NOW()),
  ('WILLIAM CYRILO MONTEIRO', 'will.monteiro@hotmail.com', '5511956474052', 'SP', 'Adriano Luiz Cherubini Pompeo', NULL, 'WILLIAM CYRILO MONTEIRO', 17078, true, NOW()),
  ('WILLIAM MARTINS DE OLIVEIRA', 'Oliveiraw76@gmail.com', '5511948786930', 'SP', 'Adriano Luiz Cherubini Pompeo', NULL, 'WILLIAM MARTINS DE OLIVEIRA', 13998, true, NOW()),
  ('WILLIAM PAULO DEBIEN ARISIO', 'william.arisio@positivo.com.br', '5514991994600', 'SP', 'Joyce Gomes Rodrigues', NULL, 'WILLIAM PAULO DEBIEN ARISIO', 17577, true, NOW()),
  ('WILLIANS SANTOS DE PANTAS', 'williansp@positivo.com.br', '5511951507338', 'SP', 'Adriano Luiz Cherubini Pompeo', NULL, 'WILLIANS SANTOS DE PANTAS', 16536, true, NOW()),
  ('WILSON JOSE DE SANTANA', 'wsantana@positivo.com.br', '5511989968040', 'SP', 'Adriano Luiz Cherubini Pompeo', NULL, 'WILSON JOSE DE SANTANA', 10953, true, NOW()),
  ('YURI NOGUEIRA', 'yurinogueira194@gmail.com', '5511953392363', 'SP', 'Thiago Cardoso da Silva', NULL, 'YURI NOGUEIRA', 17033, true, NOW()),
  ('MARCO ANTÔNIO FERNANDES', NULL, NULL, 'SP', 'Antonio Carlos Sant''anna', NULL, 'MARCO ANTÔNIO FERNANDES', 14862, true, NOW()),
  ('FELIPE DE ANAJAZ MARTINS NEIVA', NULL, NULL, 'SP', 'Adriano Luiz Cherubini Pompeo', NULL, 'FELIPE DE ANAJAZ MARTINS NEIVA', 17447, true, NOW()),
  ('LUCAS VINICIUS ALVES GONÇALVES', NULL, NULL, 'SP', 'Adriano Luiz Cherubini Pompeo', NULL, 'LUCAS VINICIUS ALVES GONÇALVES', 17510, true, NOW()),
  ('Joao Victor Rigo', NULL, NULL, 'SP', 'Cristiane Aparecida de Almeida', NULL, 'JOAO VICTOR RIGO', 17324, true, NOW()),
  ('Rodrigo Nardi Morais', NULL, NULL, 'SP', 'Cristiane Aparecida de Almeida', NULL, 'RODRIGO NARDI MORAIS', 17455, true, NOW()),
  ('Junior Batista De Souza', NULL, NULL, 'SP', 'Cristiane Aparecida de Almeida', NULL, 'JUNIOR BATISTA DE SOUZA', 17635, true, NOW()),
  ('Jafherson Kalliu De Matos Oliveira', NULL, NULL, 'SP', 'Joyce Gomes Rodrigues', NULL, 'JAFHERSON KALLIU DE MATOS OLIVEIRA', 17456, true, NOW()),
  ('Lucas Ferreira Tolentino', NULL, NULL, 'SP', 'Joyce Gomes Rodrigues', NULL, 'LUCAS FERREIRA TOLENTINO', 17380, true, NOW()),
  ('Felipe Franca Dos Santos', NULL, NULL, 'SP', 'Adriano Luiz Cherubini Pompeo', NULL, 'FELIPE FRANCA DOS SANTOS', 16888, true, NOW()),
  ('Rodrigo Maraviglia Occhini', NULL, NULL, 'SP', 'Thiago Cardoso da Silva', NULL, 'RODRIGO MARAVIGLIA OCCHINI', 17625, true, NOW()),
  ('JAELSON PAULO DE JESUS', 'JAELSON_PAULO@HOTMAIL.COM', NULL, 'SP', 'RENATO DA SILVA SUCUPIRA', NULL, 'JAELSON PAULO DE JESUS', 13370, true, NOW()),
  ('LUIS FERNANDO GAZOLA', 'LUIS.GAZOLA@POSITIVO.COM.BR', '5512988714009', 'SP', 'LEANDRO MONTEIRO FERNANDES', NULL, 'LUIS FERNANDO GAZOLA', 17651, true, NOW()),
  ('JAKELINE MEYRE DE CASTRO', 'jakelinec@positivo.com.br', '5563999518524', 'TO', 'Everton Renato Schendroski Bulhessich', NULL, 'JAKELINE MEYRE DE CASTRO', 15851, true, NOW()),
  ('OLIABE MOURA DE CASTRO', 'oliabec@positivo.com.br', NULL, 'TO', 'Everton Renato Schendroski Bulhessich', NULL, 'OLIABE MOURA DE CASTRO', 17044, true, NOW()),
  ('PAULO VICTOR MATOS LÔLA', 'pvictor@positivo.com.br', '5563984053187', 'TO', 'Everton Renato Schendroski Bulhessich', NULL, 'PAULO VICTOR MATOS LÔLA', 15850, true, NOW()),
  ('RAFAEL DA SILVA NASCIMENTO', 'rafaeln@positivo.com.br', '5563999775027', 'TO', 'Everton Renato Schendroski Bulhessich', NULL, 'RAFAEL DA SILVA NASCIMENTO', 15852, true, NOW()),
  ('JEFFERSON LUIS CAMPELO DA COSTA', 'jefferson.costa@positivo.com.br', '5563981069240', 'TO', 'Everton Renato Schendroski Bulhessich', NULL, 'JEFFERSON LUIS CAMPELO DA COSTA', 17628, true, NOW())
ON CONFLICT (name) DO UPDATE SET
  phone = EXCLUDED.phone,
  region = EXCLUDED.region,
  supervisor_name = EXCLUDED.supervisor_name,
  databricks_name = EXCLUDED.databricks_name,
  databricks_id = EXCLUDED.databricks_id,
  updated_at = NOW();